### ISSUE TITLE
What About Next.js?

### ISSUE THREAD

**Issue by LockeAG** [bstaruk/starbase-react#7]
I'm a super fan of Starbase. And I really use it everyday for start  a quick project.

React+Next is much simpler and effective and SSR by default...and the other plus, you can get the SEO the right way.. SEO is important everywhere... don't imagine why... </sarcasm off={off}>

Is there any plan of a starbase-react-next boilerplate with Next.js??

**Comment by bstaruk** [comment]
Hey @LockeAG - thanks for reaching out :)

Admittedly, the bulk of my attention has been spent on the vanilla [starbase](https://github.com/bstaruk/starbase) project over the past couple months, and there is a pretty good amount of porting-over I need to do for starbase-react.

Things like webpack 4, postcss-extend, and a bunch of build tweaks/upgrades are missing, and I need to get those ported over before I can begin exploring new libraries here.

I am going to keep this issue open because I'm always down for playing with new tech, but I do want to be transparent and honest in the fact that this may take at least a few weeks for me to begin looking into.

**Comment by LockeAG** [comment]
@bstaruk Happy to help with whatever I'm useful! 

Thank you for all!

**Comment by bstaruk** [comment]
Closing the issue, as it's a request for a new repository and not something that pertains to starbase-react.
